/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vendingmachineassignment;

import static vendingmachineassignment.vendingInterface.fiftyCent;
import static vendingmachineassignment.vendingInterface.pepsiStock;
import static vendingmachineassignment.vendingInterface.upStock;
import static vendingmachineassignment.vendingInterface.orangeStock;
import static vendingmachineassignment.vendingInterface.lemonStock;
import static vendingmachineassignment.vendingInterface.oneEuro;
import static vendingmachineassignment.vendingInterface.tenCent;
import static vendingmachineassignment.vendingInterface.totalMoney;
import static vendingmachineassignment.vendingInterface.twentyCent;
import static vendingmachineassignment.vendingInterface.twoEuro;

/**
 *
 * @author oras
 */
public class maintenanceView extends javax.swing.JFrame {
    
    public static double roundMoney(double money){
        money = Math.round(money * 100)/100.0;
        return money;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(maintenanceView.class.getName());
    

    /**
     * Creates new form maintenanceView
     */
    public maintenanceView() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextPepsiStock = new javax.swing.JTextField();
        jTextUpStock = new javax.swing.JTextField();
        jTextOrangeStock = new javax.swing.JTextField();
        jTextLemonStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextTotalMoney = new javax.swing.JTextField();
        jButtonCalc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jText2EurDisplay = new javax.swing.JTextField();
        jText1EurDisplay = new javax.swing.JTextField();
        jText50CentDisplay = new javax.swing.JTextField();
        jText20CentDisplay = new javax.swing.JTextField();
        jText10CentDisplay = new javax.swing.JTextField();
        jButtonRestock = new javax.swing.JButton();
<<<<<<< HEAD
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
=======

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
>>>>>>> origin/main

        jButtonBack.setBackground(new java.awt.Color(255, 204, 153));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pepsi Stock: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("7Up Stock:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 129, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Club Orange Stock:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Club Lemon Stock:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 201, -1, -1));
=======

        jLabel1.setText("Pepsi Stock: ");

        jLabel2.setText("7Up Stock:");

        jLabel3.setText("Club Orange Stock:");

        jLabel4.setText("Club Lemon Stock:");
>>>>>>> origin/main

        jTextPepsiStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPepsiStockActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(jTextPepsiStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 90, 71, -1));
        getContentPane().add(jTextUpStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 126, 71, -1));
=======
>>>>>>> origin/main

        jTextOrangeStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOrangeStockActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(jTextOrangeStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 162, 71, -1));
        getContentPane().add(jTextLemonStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 198, 71, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Money:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));
        getContentPane().add(jTextTotalMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 71, -1));
=======

        jLabel5.setText("Total Money:");
>>>>>>> origin/main

        jButtonCalc.setBackground(new java.awt.Color(153, 255, 153));
        jButtonCalc.setText("Calculate");
        jButtonCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(jButtonCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 276, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("€2.00 coins:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 93, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("€1.00 coins:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 129, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("€0.50 coins:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 165, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("€0.20 coins:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 201, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("€0.10 coins:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 234, -1, -1));
        getContentPane().add(jText2EurDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 90, 71, -1));
        getContentPane().add(jText1EurDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 126, 71, -1));
        getContentPane().add(jText50CentDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 162, 71, -1));
        getContentPane().add(jText20CentDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 198, 71, -1));
        getContentPane().add(jText10CentDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 234, 71, -1));
=======

        jLabel6.setText("€2.00 coins:");

        jLabel7.setText("€1.00 coins:");

        jLabel8.setText("€0.50 coins:");

        jLabel9.setText("€0.20 coins:");

        jLabel10.setText("€0.10 coins:");
>>>>>>> origin/main

        jButtonRestock.setBackground(new java.awt.Color(153, 153, 255));
        jButtonRestock.setText("Restock");
        jButtonRestock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestockActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(jButtonRestock, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 276, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingmachineassignment/maintanancelayout.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
=======

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jButtonCalc)
                .addGap(18, 18, 18)
                .addComponent(jButtonRestock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextPepsiStock, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21)
                                .addComponent(jTextLemonStock, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextUpStock, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextOrangeStock, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jText10CentDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jText50CentDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jText2EurDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jText1EurDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jText20CentDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonBack)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextPepsiStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jText2EurDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextUpStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jText1EurDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextOrangeStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jText50CentDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextLemonStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jText20CentDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jText10CentDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalc)
                    .addComponent(jButtonRestock))
                .addContainerGap(21, Short.MAX_VALUE))
        );
>>>>>>> origin/main

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        vendingInterface j = new vendingInterface();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextPepsiStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPepsiStockActionPerformed
    }//GEN-LAST:event_jTextPepsiStockActionPerformed

    private void jButtonCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcActionPerformed
        jTextPepsiStock.setText(pepsiStock + "");
        jTextUpStock.setText(upStock + "");
        jTextOrangeStock.setText(orangeStock + "");
        jTextLemonStock.setText(lemonStock + "");
        jTextTotalMoney.setText(totalMoney + "");
        jText2EurDisplay.setText(twoEuro + "");
        jText1EurDisplay.setText(oneEuro + "");
        jText50CentDisplay.setText(fiftyCent + "");
        jText20CentDisplay.setText(twentyCent + "");
        jText10CentDisplay.setText(tenCent + "");
    }//GEN-LAST:event_jButtonCalcActionPerformed

    private void jButtonRestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestockActionPerformed
        restockPage j = new restockPage();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRestockActionPerformed

    private void jTextOrangeStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOrangeStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextOrangeStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new maintenanceView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCalc;
    private javax.swing.JButton jButtonRestock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel11;
=======
>>>>>>> origin/main
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jText10CentDisplay;
    private javax.swing.JTextField jText1EurDisplay;
    private javax.swing.JTextField jText20CentDisplay;
    private javax.swing.JTextField jText2EurDisplay;
    private javax.swing.JTextField jText50CentDisplay;
    private javax.swing.JTextField jTextLemonStock;
    private javax.swing.JTextField jTextOrangeStock;
    private javax.swing.JTextField jTextPepsiStock;
    private javax.swing.JTextField jTextTotalMoney;
    private javax.swing.JTextField jTextUpStock;
    // End of variables declaration//GEN-END:variables
}
