/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vendingmachineassignment;

import static vendingmachineassignment.vendingInterface.pepsiStock;
import static vendingmachineassignment.vendingInterface.upStock;
import static vendingmachineassignment.vendingInterface.orangeStock;
import static vendingmachineassignment.vendingInterface.lemonStock;
import javax.swing.JFrame;

/**
 *
 * @author oras
 */
public class restockPage extends JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(restockPage.class.getName());

    /**
     * Creates new form restockPage
     */
    public restockPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextPepsiRestock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextUpRestock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextOrangeRestock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextLemonRestock = new javax.swing.JTextField();
        jButtonConfirm = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pepsi Restock:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 36, -1, -1));
        getContentPane().add(jTextPepsiRestock, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 33, 71, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("7Up Restock:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 69, -1, -1));
        getContentPane().add(jTextUpRestock, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 66, 71, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Club Orange Restock:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 105, -1, -1));
        getContentPane().add(jTextOrangeRestock, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 102, 71, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Club Lemon Restock:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 141, -1, -1));
        getContentPane().add(jTextLemonRestock, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 138, 71, -1));

        jButtonConfirm.setBackground(new java.awt.Color(153, 255, 153));
        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 256, -1, -1));

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 256, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingmachineassignment/maintanancelayout.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        maintenanceView j = new maintenanceView();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        int pepsi = Integer.parseInt(jTextPepsiRestock.getText());
        jTextPepsiRestock.setText("");
        pepsiStock += pepsi;
        int up = Integer.parseInt(jTextUpRestock.getText());
        jTextUpRestock.setText("");
        upStock += up;
        int orange = Integer.parseInt(jTextOrangeRestock.getText());
        jTextOrangeRestock.setText("");
        orangeStock += orange;
        int lemon = Integer.parseInt(jTextLemonRestock.getText());
        jTextLemonRestock.setText("");
        lemonStock += lemon;
        
        maintenanceView j = new maintenanceView();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new restockPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextLemonRestock;
    private javax.swing.JTextField jTextOrangeRestock;
    private javax.swing.JTextField jTextPepsiRestock;
    private javax.swing.JTextField jTextUpRestock;
    // End of variables declaration//GEN-END:variables
}
