/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vendingmachineassignment;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author oras
 */
public class VendingInterface extends javax.swing.JFrame {
    
  //money declaration   
    public static int twoEuro = 3;
    public static int oneEuro = 7;
    public static int fiftyCent = 4;
    public static int twentyCent = 5;
    public static int tenCent = 8;
    
    //Calculate the total money via the variables as opposed to hardcoding
    public static double totalMoney = 16.8;
    public static double moneyIn = 0.0;
    public static double totalPrice = 0.0;
    public static double change = 0.0;
    
    public static double roundMoney(double money){
        money = Math.round(money * 100)/100.0;
        return money;
    }
    
    /*public static double roundPrice(double price){
        totalPrice = Math.round(totalPrice * 200)/100.0;
        return price;
    }*/
    
    
    
  //stock declaration
    public static int pepsiStock = 5;
    public static int upStock = 4;
    public static int orangeStock = 7;
    public static int lemonStock = 3;
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VendingInterface.class.getName());
    private Component frame;

    /**
     * Creates new form vendingInterface
     */
    public VendingInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPepsi = new javax.swing.JButton();
        jButtonUp = new javax.swing.JButton();
        jButtonOrange = new javax.swing.JButton();
        jButtonLemon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonTwoEuro = new javax.swing.JButton();
        jButtonOneEuro = new javax.swing.JButton();
        jButtonFiftyCent = new javax.swing.JButton();
        jButtonTwentyCent = new javax.swing.JButton();
        jButtonTenCent = new javax.swing.JButton();
        listProductsSelect = new java.awt.List();
        jButtonConfirm = new javax.swing.JButton();
        jButtonClearAll = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        listMoneyIn = new java.awt.List();
        jLabel6 = new javax.swing.JLabel();
        jTextMoneyIn = new javax.swing.JTextField();
        jTextTotalCost = new javax.swing.JTextField();
        jTextChange = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonMaintenance = new javax.swing.JButton();
        jPepsiAvailable = new javax.swing.JRadioButton();
        jUpAvailable = new javax.swing.JRadioButton();
        jOrangeAvailable = new javax.swing.JRadioButton();
        jLemonAvailable = new javax.swing.JRadioButton();
        jButtonClearMoney = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPepsi.setBackground(new java.awt.Color(0, 0, 255));
        jButtonPepsi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPepsi.setContentAreaFilled(false);
        jButtonPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPepsiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 70));

        jButtonUp.setBackground(new java.awt.Color(102, 255, 102));
        jButtonUp.setContentAreaFilled(false);
        jButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 120, 70));

        jButtonOrange.setBackground(new java.awt.Color(255, 204, 102));
        jButtonOrange.setContentAreaFilled(false);
        jButtonOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrangeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 130, 70));

        jButtonLemon.setBackground(new java.awt.Color(255, 255, 153));
        jButtonLemon.setContentAreaFilled(false);
        jButtonLemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLemonActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 130, 70));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("€1.70");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("€1.50");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("€1.00");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("€1.00");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        jButtonTwoEuro.setText("€2.00");
        jButtonTwoEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwoEuroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTwoEuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 198, -1, -1));

        jButtonOneEuro.setText("€1.00");
        jButtonOneEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneEuroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOneEuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 234, -1, -1));

        jButtonFiftyCent.setText("€0.50");
        jButtonFiftyCent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiftyCentActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFiftyCent, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 270, -1, -1));

        jButtonTwentyCent.setText("€0.20");
        jButtonTwentyCent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwentyCentActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTwentyCent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 198, -1, -1));

        jButtonTenCent.setText("€0.10");
        jButtonTenCent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTenCentActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTenCent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 234, -1, -1));

        listProductsSelect.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(listProductsSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 198, 73, 100));

        jButtonConfirm.setBackground(new java.awt.Color(153, 255, 153));
        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 304, -1, -1));

        jButtonClearAll.setBackground(new java.awt.Color(255, 102, 102));
        jButtonClearAll.setText("Clear All");
        jButtonClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearAllActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClearAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 80, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Price: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 198, -1, -1));

        jButtonExit.setBackground(new java.awt.Color(153, 0, 0));
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        listMoneyIn.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(listMoneyIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 198, 73, 96));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Money In:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 198, -1, -1));
        getContentPane().add(jTextMoneyIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 222, 60, -1));
        getContentPane().add(jTextTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 222, 60, -1));
        getContentPane().add(jTextChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 222, 71, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Change");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 198, -1, -1));

        jButtonMaintenance.setBackground(new java.awt.Color(153, 153, 255));
        jButtonMaintenance.setText("Maintenance");
        jButtonMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaintenanceActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        jPepsiAvailable.setForeground(new java.awt.Color(255, 255, 255));
        jPepsiAvailable.setSelected(true);
        jPepsiAvailable.setText("Available");
        jPepsiAvailable.setEnabled(false);
        jPepsiAvailable.setFocusPainted(false);
        getContentPane().add(jPepsiAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jUpAvailable.setForeground(new java.awt.Color(255, 255, 255));
        jUpAvailable.setSelected(true);
        jUpAvailable.setText("Available");
        jUpAvailable.setEnabled(false);
        jUpAvailable.setFocusPainted(false);
        getContentPane().add(jUpAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jOrangeAvailable.setForeground(new java.awt.Color(255, 255, 255));
        jOrangeAvailable.setSelected(true);
        jOrangeAvailable.setText("Available");
        jOrangeAvailable.setEnabled(false);
        jOrangeAvailable.setFocusPainted(false);
        getContentPane().add(jOrangeAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLemonAvailable.setForeground(new java.awt.Color(255, 255, 255));
        jLemonAvailable.setSelected(true);
        jLemonAvailable.setText("Available");
        jLemonAvailable.setContentAreaFilled(false);
        jLemonAvailable.setEnabled(false);
        jLemonAvailable.setFocusPainted(false);
        getContentPane().add(jLemonAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jButtonClearMoney.setBackground(new java.awt.Color(255, 102, 0));
        jButtonClearMoney.setText("Clear Money");
        jButtonClearMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearMoneyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClearMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingmachineassignment/vendingmachinelayout.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTwoEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwoEuroActionPerformed
        twoEuro ++;
        totalMoney += 2.0;
        moneyIn += 2.0;
        moneyIn = roundMoney(moneyIn);
        listMoneyIn.add("€2.00");
        jTextMoneyIn.setText(moneyIn + "");
    }//GEN-LAST:event_jButtonTwoEuroActionPerformed

    private void jButtonOneEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneEuroActionPerformed
        oneEuro ++;
        totalMoney += 1.0; 
        moneyIn += 1.0;
        moneyIn = roundMoney(moneyIn);
        listMoneyIn.add("€1.00");
        jTextMoneyIn.setText(moneyIn + "");
    }//GEN-LAST:event_jButtonOneEuroActionPerformed

    private void jButtonFiftyCentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiftyCentActionPerformed
        fiftyCent ++;
        totalMoney += 0.5;
        moneyIn += 0.5;
        moneyIn = roundMoney(moneyIn);
        listMoneyIn.add("€0.50");
        jTextMoneyIn.setText(moneyIn + "");
    }//GEN-LAST:event_jButtonFiftyCentActionPerformed

    private void jButtonTwentyCentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwentyCentActionPerformed
        twentyCent ++;
        totalMoney += 0.2;
        moneyIn += 0.2;
        moneyIn = roundMoney(moneyIn);
        listMoneyIn.add("€0.20");
        jTextMoneyIn.setText(moneyIn + "");
    }//GEN-LAST:event_jButtonTwentyCentActionPerformed

    private void jButtonTenCentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTenCentActionPerformed
        tenCent ++;
        totalMoney += 0.1;
        moneyIn += 0.1;
        moneyIn = roundMoney(moneyIn);
        listMoneyIn.add("€0.10");
        jTextMoneyIn.setText(moneyIn + "");
    }//GEN-LAST:event_jButtonTenCentActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllActionPerformed
        //clear all fields
        listMoneyIn.removeAll();
        listProductsSelect.removeAll();
        jTextTotalCost.setText("");
        jTextMoneyIn.setText("");
        //reset Money in system
        twoEuro = 3;
        oneEuro = 7;
        fiftyCent = 4;
        twentyCent = 5;
        tenCent = 8;
        totalMoney = 16.8;
        moneyIn = 0.0;
        totalPrice = 0.0;
        change = 0.0;
        //reset stock in system
        pepsiStock = 5;
        upStock = 4;
        orangeStock = 7;
        lemonStock = 3;
    }//GEN-LAST:event_jButtonClearAllActionPerformed

    private void jButtonPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPepsiActionPerformed
        if (pepsiStock > 0){
            pepsiStock --;
            listProductsSelect.add("Pepsi");
            totalPrice += 1.7;
            totalPrice = roundMoney(totalPrice);
            jTextTotalCost.setText(totalPrice + "");
            jPepsiAvailable.setSelected(true);
        }else {
            jPepsiAvailable.setSelected(false);
            JOptionPane.showMessageDialog(frame, "Out of Stock!");
        }
    }//GEN-LAST:event_jButtonPepsiActionPerformed

    private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
        if (upStock > 0){
            upStock --;
            listProductsSelect.add("7Up");
            totalPrice += 1.5;
            totalPrice = roundMoney(totalPrice);
            jTextTotalCost.setText(totalPrice + "");
            jUpAvailable.setSelected(true);
        }else {
            jUpAvailable.setSelected(false);
            JOptionPane.showMessageDialog(frame, "Out of Stock!");

        }
    }//GEN-LAST:event_jButtonUpActionPerformed

    private void jButtonOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrangeActionPerformed
        if (orangeStock > 0){
            orangeStock --;
            listProductsSelect.add("ClubOrange");
            totalPrice += 1.0;
            totalPrice = roundMoney(totalPrice);
            jTextTotalCost.setText(totalPrice + "");
            jOrangeAvailable.setSelected(true);
        }else {
            jOrangeAvailable.setSelected(false);
            JOptionPane.showMessageDialog(frame, "Out of Stock!");
        }
    }//GEN-LAST:event_jButtonOrangeActionPerformed

    private void jButtonLemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLemonActionPerformed
        if (lemonStock > 0){
            lemonStock --;
            listProductsSelect.add("Club Lemon");
            totalPrice += 1.0;
            totalPrice = roundMoney(totalPrice);
            jTextTotalCost.setText(totalPrice + "");
            jLemonAvailable.setSelected(true);
        }else {
            jLemonAvailable.setSelected(false);
            JOptionPane.showMessageDialog(frame, "Out of Stock!");
        }
    }//GEN-LAST:event_jButtonLemonActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        if (moneyIn >= totalPrice){
            change = moneyIn - totalPrice;
            change = roundMoney(change);
            jTextChange.setText(change + "");
            totalMoney += totalPrice;
            totalMoney = roundMoney(totalMoney);
            moneyIn = 0.0;
            totalPrice = 0.0;
            listMoneyIn.removeAll();
            listProductsSelect.removeAll();
            }else if(moneyIn < totalPrice){
                JOptionPane.showMessageDialog(frame, "Not enough money!.");
        }
        
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaintenanceActionPerformed
        MaintenanceInterface j = new MaintenanceInterface();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMaintenanceActionPerformed

    private void jButtonClearMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearMoneyActionPerformed
        //clear fields
        listMoneyIn.removeAll();
        jTextMoneyIn.setText("");
        //clear money
        twoEuro = 3;
        oneEuro = 7;
        fiftyCent = 4;
        twentyCent = 5;
        tenCent = 8;
        totalMoney = 16.8;
        moneyIn = 0.0;
        totalPrice = 0.0;
        change = 0.0;
    }//GEN-LAST:event_jButtonClearMoneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VendingInterface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JButton jButtonClearMoney;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFiftyCent;
    private javax.swing.JButton jButtonLemon;
    private javax.swing.JButton jButtonMaintenance;
    private javax.swing.JButton jButtonOneEuro;
    private javax.swing.JButton jButtonOrange;
    private javax.swing.JButton jButtonPepsi;
    private javax.swing.JButton jButtonTenCent;
    private javax.swing.JButton jButtonTwentyCent;
    private javax.swing.JButton jButtonTwoEuro;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jLemonAvailable;
    private javax.swing.JRadioButton jOrangeAvailable;
    private javax.swing.JRadioButton jPepsiAvailable;
    private javax.swing.JTextField jTextChange;
    private javax.swing.JTextField jTextMoneyIn;
    private javax.swing.JTextField jTextTotalCost;
    private javax.swing.JRadioButton jUpAvailable;
    private java.awt.List listMoneyIn;
    private java.awt.List listProductsSelect;
    // End of variables declaration//GEN-END:variables
}
